### ISSUE TITLE
rpm -E %{?dist} returns wrong distro on RHEL 7.3

### ISSUE THREAD

**Issue by gilShin** [lago-project/lago-demo#14]
I have run the script "install_lago.sh" on RHEL 7.3 and got an error message that there's no such distro el7_3. 
Probably the "rpm -E %{?dist}" doesn't do it's work properly.

**Comment by nvgoldin** [comment]
Thanks, will look into it.
1. Can you paste ``cat /etc/*release*`` on the machine?
2. Also ``rpm -qa | grep redhat`` would be useful.
3. Is this under mock?

**Comment by nvgoldin** [comment]
@gilShin  - Can you check if https://raw.githubusercontent.com/nvgoldin/lago-demo/1ca3edee87dee674163f1afcf5483d9bac7f6f8e/install_scripts/install_lago.sh resolves the issue?

Even though it would be useful to debug this, as it looks like it contradicts Fedora packaging guideline for the ``dist`` macro:
https://fedoraproject.org/wiki/Packaging:DistTag

**Comment by gilShin** [comment]
Works

Thanks
