### ISSUE TITLE
check-patch: Running existing env with new lago version

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago-demo#35]
The test should check that an env that was created with the current stable lago version, can be used with the version that we are going to release.

This check will ensure that we don't break the workflow of our users.

**Comment by ifireball** [comment]
If you're talking about OST, we'll probably take care of that as part of the change queue work, no need to do a Lago-specific effort here.

**Comment by ifireball** [comment]
If you're talking about OST, we'll probably take care of that as part of the change queue work, no need to do a Lago-specific effort here.

**Comment by ifireball** [comment]
Here is a tracking ticket on the CI side: https://ovirt-jira.atlassian.net/browse/OVIRT-1498

**Comment by nvgoldin** [comment]
@ifireball - cool, though I think @gbenhaim meant a flow such as: ``install lago -> lago init -> lago start -> lago stop -> upgrade to latest unstable -> lago start``, if that is the intention - I definitely agree, but I wouldn't label it as a bug more like an enhacement.

With that said, I feel the 'lago-demo' CI is not the suitable place for all these tests we're running, maybe we should consider integrating these tests into Lago CI, including the install_script.sh itself(maybe under a ``contrib`` directory or something). We could make the check-patch/check-merged scripts a little smarter to detect changes to the script.

**Comment by gbenhaim** [comment]
https://github.com/lago-project/lago-demo/pull/44
